-- 자기 자신을 부모로 가지는 경우가 없는 요소들을 담은 테이블
WITH TEMP AS (
    SELECT ITEM_ID
    FROM ITEM_TREE T1
    WHERE ITEM_ID NOT IN (
        SELECT PARENT_ITEM_ID
        FROM ITEM_TREE T2
        WHERE PARENT_ITEM_ID IS NOT NULL
    )
)

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I 
JOIN TEMP T
ON I.ITEM_ID = T.ITEM_ID
ORDER BY ITEM_ID DESC