WITH TEMP AS (
    SELECT I.ANIMAL_ID, I.NAME, (O.DATETIME - I.DATETIME) AS TERM
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY TERM DESC
)

SELECT T.ANIMAL_ID, T.NAME
FROM TEMP T
LIMIT 2

