-- 코드를 입력하세요
WITH RECURSIVE TEMP AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TEMP
    WHERE HOUR<23
)

SELECT T.HOUR, IFNULL(Q.COUNT, 0) AS COUNT
FROM TEMP T
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS 
    GROUP BY HOUR
    ORDER BY HOUR
) AS Q
ON T.HOUR = Q.HOUR
