-- 코드를 입력하세요
WITH TEMP AS (
    SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
    WHERE B.STATUS = 'DONE'
    GROUP BY U.USER_ID
    ORDER BY TOTAL_SALES
)

SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM TEMP
WHERE TOTAL_SALES >= 700000