WITH TEMP AS (
    SELECT 
        BOARD_ID,
        RANK() OVER(ORDER BY VIEWS DESC) AS RNK
    FROM USED_GOODS_BOARD B
)

SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM TEMP T
JOIN USED_GOODS_FILE F
ON T.BOARD_ID = F.BOARD_ID
WHERE RNK = 1
ORDER BY F.FILE_ID DESC