-- 코드를 입력하세요
SELECT S.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT S
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자','국','김치','식용유')
    ORDER BY PRICE DESC
) F
ON S.PRICE = F.MAX_PRICE AND S.CATEGORY = F.CATEGORY
ORDER BY MAX_PRICE DESC;


