-- 물고기 유형마다의 평균 길이 구하는 테이블
WITH TEMP AS (
    SELECT FISH_TYPE, AVG(CASE
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH END
        ) AS AVERAGE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVERAGE >= 33
)

SELECT COUNT(*) AS FISH_COUNT, MAX(I.LENGTH) AS MAX_LENGTH, I.FISH_TYPE
FROM FISH_INFO I
JOIN TEMP T
ON I.FISH_TYPE = T.FISH_TYPE
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE ASC



